/**
 * The first validated career library: role blueprints and their sources.
 *
 * Scope is deliberate. These are the career directions that actually recur in
 * the live hypothesis set (consulting, the finance ladder, product and
 * engineering, marketing and sales, founder work, the clinical and health
 * system cluster, policy research, nonprofit and education programming, law,
 * real estate) rather than an attempt to cover every career.
 *
 * Two rules this file holds:
 *  - `sources` are real, checkable publications only: O*NET occupational
 *    summaries and the BLS Occupational Outlook Handbook. Nothing invented, and
 *    no professional reviews are asserted anywhere in this library, so every
 *    experiment lands at Source Grounded and never at Professionally Reviewed.
 *  - `characteristics` use the same dimension ids as the evidence model, so an
 *    experiment mapped to a dimension can be read against a student's evidence
 *    on that dimension without a translation layer.
 *
 * characteristics rows are [dimension_id, importance, note, simulatable].
 */

const onet = (name, url) => ({ source_type: 'onet', source_name: `O*NET OnLine: ${name}`, source_url: url });
const bls = (name, url) => ({ source_type: 'bls', source_name: `BLS Occupational Outlook Handbook: ${name}`, source_url: url });

export const CAREERS = [
  {
    key: 'management_consulting',
    title: 'Management Consulting',
    family: 'Strategy and advisory',
    seniority_scope: 'Analyst or associate, first two years',
    match_terms: ['management consulting', 'consulting', 'strategy consult', 'health policy consultant', 'educational consulting'],
    core_tasks: [
      'Break a client question into parts that can be answered separately',
      'Gather data from client systems, interviews and public sources',
      'Build the analysis that decides the answer, usually in a spreadsheet',
      'Turn the analysis into slides a partner will present',
      'Interview client staff to understand how the business actually runs',
    ],
    entry_level_responsibilities: [
      'Own two or three slides or one workstream, not the whole answer',
      'Clean and reconcile client data nobody has checked',
      'Write up interview notes the same day',
      'Chase missing numbers from client contacts',
    ],
    typical_decisions: [
      'Which slice of the problem is worth the team\u2019s remaining time',
      'Whether a data set is trustworthy enough to base a recommendation on',
      'What to leave out of a deck so the argument stays clear',
    ],
    common_deliverables: ['Slide decks', 'Excel models', 'Interview write-ups', 'Client-ready summaries of findings'],
    tools_used: ['Excel', 'PowerPoint', 'Client data extracts', 'Market and survey data'],
    skills_used: ['Structured problem solving', 'Quantitative analysis', 'Written and verbal communication', 'Client management'],
    work_environment: 'Small teams, client sites or remote, with a partner reviewing work on short cycles. Travel varies by firm and client.',
    work_schedule_notes: 'Long and uneven hours driven by client deadlines. Evening turnarounds before a client meeting are normal rather than exceptional.',
    common_misconceptions: [
      'That the work is mostly strategy. In the first two years it is mostly data cleaning, slide production and interview notes.',
      'That you present to executives early. Junior staff usually watch someone else present their analysis.',
      'That the difficulty is intellectual. Most of it is getting usable data out of a client organisation.',
    ],
    cannot_be_simulated: [
      'A partner changing the question two days before the deadline',
      'Client politics, where the right answer is not the one being asked for',
      'Sustained travel and living out of a hotel',
    ],
    characteristics: [
      ['analytical_depth', 'high', 'Every deliverable rests on an analysis you built.', true],
      ['ambiguity_tolerance', 'high', 'Questions arrive underspecified and scope moves.', true],
      ['quantitative_intensity', 'high', 'Spreadsheet work daily, rarely advanced maths.', true],
      ['detail_orientation', 'high', 'A wrong number in a partner\u2019s deck is a serious error.', true],
      ['high_pressure_pace', 'high', 'Deadlines are external and immovable.', true],
      ['client_interaction', 'high', 'Interviews and working sessions with client staff.', true],
      ['teamwork', 'high', 'Nothing is produced alone; work is reviewed constantly.', true],
      ['presenting', 'medium', 'You defend your analysis internally first.', true],
      ['writing', 'medium', 'Findings must be written so a partner can use them.', true],
      ['persuasion', 'medium', 'You argue for a recommendation internally.', true],
      ['repetitive_precision', 'medium', 'Data reconciliation is repetitive and exacting.', true],
      ['autonomy', 'low', 'Direction comes from the engagement manager.', true],
    ],
    sources: [
      onet('Management Analysts (13-1111.00)', 'https://www.onetonline.org/link/summary/13-1111.00'),
      bls('Management Analysts', 'https://www.bls.gov/ooh/business-and-financial/management-analysts.htm'),
    ],
  },

  {
    key: 'investment_banking',
    title: 'Investment Banking',
    family: 'Finance',
    seniority_scope: 'Analyst, first two years',
    match_terms: ['investment banking', 'boutique investment bank', 'ib analyst', 'm&a advisory', 'capital markets'],
    core_tasks: [
      'Build and maintain operating, valuation and transaction models',
      'Produce pitch books and client materials',
      'Run comparable company and precedent transaction analysis',
      'Tie out documents so every number agrees with its source',
      'Support live deal processes, data rooms and diligence lists',
    ],
    entry_level_responsibilities: [
      'Own model mechanics and the accuracy of every figure',
      'Format and proof pitch materials, often late at night',
      'Maintain trackers and comparable sets',
      'Turn senior comments around quickly and exactly as marked',
    ],
    typical_decisions: [
      'Which comparable companies genuinely belong in the set',
      'Which assumptions to flag rather than resolve yourself',
      'What to check first when two sources disagree',
    ],
    common_deliverables: ['Valuation models', 'Pitch books', 'Comparable company analyses', 'Diligence summaries'],
    tools_used: ['Excel', 'PowerPoint', 'Capital IQ or FactSet', 'Company filings'],
    skills_used: ['Financial modelling', 'Accounting fluency', 'Extreme attention to detail', 'Working under time pressure'],
    work_environment: 'Deal teams in an office, with work arriving from several senior bankers at once. Hours are the defining feature.',
    work_schedule_notes: 'Very long hours, weekend work during live processes, and little control over your own schedule.',
    common_misconceptions: [
      'That the analysis is intellectually complex. Most is standard method applied under time pressure without errors.',
      'That analysts advise clients. Client contact is mostly logistical in year one.',
      'That the hours are the only difficulty. Sustained precision when tired is harder.',
    ],
    cannot_be_simulated: [
      'Sustained sleep deprivation across months',
      'A live deal collapsing after weeks of work',
      'Having no control over when your evening ends',
    ],
    characteristics: [
      ['detail_orientation', 'high', 'Accuracy is the core competency.', true],
      ['quantitative_intensity', 'high', 'Modelling and accounting mechanics daily.', true],
      ['repetitive_precision', 'high', 'Tie-outs, formatting and comp updates repeat.', true],
      ['high_pressure_pace', 'high', 'Turnarounds measured in hours.', true],
      ['structured_environments', 'high', 'Method and format are prescribed.', true],
      ['analytical_depth', 'medium', 'Deep in mechanics, narrow in scope.', true],
      ['independent_work', 'medium', 'Long solo stretches inside a model.', true],
      ['teamwork', 'medium', 'Deal teams are small and interdependent.', true],
      ['competition', 'medium', 'Ranking and staffing are openly competitive.', false],
      ['client_interaction', 'low', 'Limited and mostly administrative early.', false],
      ['autonomy', 'low', 'Almost none at analyst level.', true],
    ],
    sources: [
      onet('Financial and Investment Analysts (13-2051.00)', 'https://www.onetonline.org/link/summary/13-2051.00'),
      bls('Financial Analysts', 'https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm'),
    ],
  },

  {
    key: 'corporate_finance_fpa',
    title: 'Corporate Finance and FP&A',
    family: 'Finance',
    seniority_scope: 'Analyst, first two years',
    match_terms: ['corporate finance', 'fp&a', 'financial planning & analysis', 'financial planning and analysis', 'investor relations', 'corporate risk', 'treasury'],
    core_tasks: [
      'Build and maintain budget and forecast models',
      'Explain variance between plan and actual results',
      'Prepare the monthly reporting pack for business leaders',
      'Partner with department heads on their spending',
      'Support annual planning cycles',
    ],
    entry_level_responsibilities: [
      'Own recurring reports and their accuracy',
      'Pull actuals from the accounting system and reconcile them',
      'Draft variance commentary for review',
      'Answer ad hoc questions from business partners',
    ],
    typical_decisions: [
      'Which variances are worth explaining and which are noise',
      'How conservative a forecast assumption should be',
      'When to escalate a number that does not make sense',
    ],
    common_deliverables: ['Monthly reporting packs', 'Budget and forecast models', 'Variance commentary', 'Business cases'],
    tools_used: ['Excel', 'ERP systems', 'Planning tools such as Anaplan or Adaptive', 'BI dashboards'],
    skills_used: ['Forecasting', 'Accounting fluency', 'Business partnering', 'Clear written explanation of numbers'],
    work_environment: 'Inside one company on a monthly and quarterly rhythm, working with non-finance managers who need the numbers explained.',
    work_schedule_notes: 'Predictable most of the month, with real crunch during close, forecast and annual planning.',
    common_misconceptions: [
      'That it is strategy work. Most of it is recurring reporting done reliably.',
      'That the numbers speak for themselves. Explaining them is most of the value.',
      'That every week is calm. Close and planning weeks are not.',
    ],
    cannot_be_simulated: [
      'The monthly close cycle repeating for years',
      'Owning a forecast you publicly committed to and missed',
      'Politics around another department\u2019s budget',
    ],
    characteristics: [
      ['quantitative_intensity', 'high', 'Numbers are the medium of the job.', true],
      ['detail_orientation', 'high', 'Reports reach executives with your name on them.', true],
      ['repetitive_precision', 'high', 'The same cycle every month.', true],
      ['structured_environments', 'high', 'Calendar-driven and process-heavy.', true],
      ['writing', 'medium', 'Variance commentary is written work.', true],
      ['client_interaction', 'medium', 'Your clients are internal business partners.', true],
      ['analytical_depth', 'medium', 'Real analysis in narrow windows.', true],
      ['ambiguity_tolerance', 'medium', 'Ad hoc questions arrive underspecified.', true],
      ['high_pressure_pace', 'medium', 'Concentrated around close and planning.', true],
      ['autonomy', 'medium', 'Ownership of your own reports grows quickly.', true],
    ],
    sources: [
      onet('Financial and Investment Analysts (13-2051.00)', 'https://www.onetonline.org/link/summary/13-2051.00'),
      bls('Financial Managers', 'https://www.bls.gov/ooh/management/financial-managers.htm'),
    ],
  },

  {
    key: 'private_equity',
    title: 'Private Equity and Growth Investing',
    family: 'Finance',
    seniority_scope: 'Associate or pre-associate exposure',
    match_terms: ['private equity', 'growth equity', 'venture capital', 'vc analyst', 'family office', 'proprietary trader', 'investment management'],
    core_tasks: [
      'Screen companies against an investment thesis',
      'Build returns models on candidate deals',
      'Run diligence workstreams with advisers and management',
      'Write investment memos for the committee',
      'Track portfolio company performance after investment',
    ],
    entry_level_responsibilities: [
      'Screen a high volume of companies, most of which are rejected',
      'Own the model and its supporting data',
      'Summarise diligence findings honestly, including the unresolved',
      'Prepare committee materials',
    ],
    typical_decisions: [
      'Whether a company is worth the team\u2019s time at all',
      'Which diligence risk is a dealbreaker and which is priceable',
      'What to write about a thesis you privately doubt',
    ],
    common_deliverables: ['Investment memos', 'Returns models', 'Diligence summaries', 'Portfolio updates'],
    tools_used: ['Excel', 'Data rooms', 'Capital IQ or PitchBook', 'Portfolio reporting tools'],
    skills_used: ['Judgement under incomplete information', 'Modelling', 'Written argument', 'Commercial diligence'],
    work_environment: 'Small investment teams, high individual expectations, and long stretches between completed deals.',
    work_schedule_notes: 'Uneven: intense during live processes, quieter between them. Deals often collapse late.',
    common_misconceptions: [
      'That most time is spent investing. Most time is spent rejecting companies.',
      'That the model decides. The written argument and diligence judgement decide.',
      'That outcomes are quick. Results play out over years.',
    ],
    cannot_be_simulated: [
      'Carrying responsibility for real capital',
      'A committee rejecting work you spent two months on',
      'Waiting years to learn whether a judgement was right',
    ],
    characteristics: [
      ['analytical_depth', 'high', 'Diligence is sustained analytical work.', true],
      ['writing', 'high', 'The memo carries the argument.', true],
      ['quantitative_intensity', 'high', 'Returns modelling underpins everything.', true],
      ['ambiguity_tolerance', 'high', 'You never have complete information.', true],
      ['detail_orientation', 'high', 'A diligence miss is a real loss.', true],
      ['risk_tolerance', 'high', 'Being wrong is visible and expensive.', false],
      ['long_project_cycles', 'high', 'Feedback arrives years later.', false],
      ['independent_work', 'medium', 'Long solo work on models and memos.', true],
      ['client_interaction', 'medium', 'Management teams and advisers.', true],
    ],
    sources: [
      onet('Financial and Investment Analysts (13-2051.00)', 'https://www.onetonline.org/link/summary/13-2051.00'),
      bls('Financial Analysts', 'https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm'),
    ],
  },

  {
    key: 'corporate_development_ma',
    title: 'Corporate Development and M&A',
    family: 'Finance',
    seniority_scope: 'Analyst or associate',
    match_terms: ['corporate development', 'internal m&a', 'corp dev', 'life sciences corporate development', 'biotech corporate development', 'corporate strategy'],
    core_tasks: [
      'Maintain a pipeline of acquisition or partnership targets',
      'Model the financial effect of a transaction on the company',
      'Coordinate diligence across internal functions',
      'Prepare materials for executives and the board',
      'Support integration planning after signing',
    ],
    entry_level_responsibilities: [
      'Own target research and the pipeline tracker',
      'Build and update transaction models',
      'Chase internal functions for diligence input',
      'Draft executive summaries',
    ],
    typical_decisions: [
      'Which targets fit the strategy well enough to raise internally',
      'How to present a deal whose numbers are marginal',
      'Which internal objection is fatal and which is manageable',
    ],
    common_deliverables: ['Transaction models', 'Board materials', 'Target landscape reviews', 'Integration plans'],
    tools_used: ['Excel', 'PowerPoint', 'Market and pipeline databases', 'Internal financial systems'],
    skills_used: ['Modelling', 'Cross-functional coordination', 'Executive communication', 'Strategic reasoning'],
    work_environment: 'A small team inside one company, working across every function and reporting close to the executive level.',
    work_schedule_notes: 'Calmer than banking between deals, comparable during a live transaction.',
    common_misconceptions: [
      'That it is banking with better hours. The coordination and internal politics are a different job.',
      'That deals are the main activity. Most pipeline work never becomes a deal.',
      'That strategy is handed to you. Often you are the one arguing for it.',
    ],
    cannot_be_simulated: [
      'Politics between functions that must all agree',
      'Presenting to a board that can kill the project',
      'Living with an integration you recommended',
    ],
    characteristics: [
      ['analytical_depth', 'high', 'Strategic and financial analysis together.', true],
      ['quantitative_intensity', 'high', 'Transaction modelling.', true],
      ['presenting', 'high', 'Executive audiences, early.', true],
      ['persuasion', 'high', 'You are selling internally, constantly.', true],
      ['teamwork', 'high', 'Every function has a say.', true],
      ['detail_orientation', 'high', 'Board materials must be exact.', true],
      ['ambiguity_tolerance', 'medium', 'Strategy questions arrive open.', true],
      ['long_project_cycles', 'medium', 'Deals take months and often die.', false],
      ['autonomy', 'medium', 'Real ownership of workstreams.', true],
    ],
    sources: [
      onet('Financial and Investment Analysts (13-2051.00)', 'https://www.onetonline.org/link/summary/13-2051.00'),
      bls('Financial Analysts', 'https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm'),
    ],
  },

  {
    key: 'wealth_management',
    title: 'Financial Planning and Wealth Management',
    family: 'Finance',
    seniority_scope: 'Paraplanner or associate adviser',
    match_terms: ['wealth management', 'financial planning & advisory', 'financial planning and wealth', 'personal financial advisor', 'financial advisor', 'private banking'],
    core_tasks: [
      'Build financial plans from a client\u2019s goals, income and obligations',
      'Model retirement, tax and insurance scenarios',
      'Prepare and sit in client review meetings',
      'Maintain client records and implement agreed changes',
      'Develop new client relationships',
    ],
    entry_level_responsibilities: [
      'Prepare plan documents and meeting materials',
      'Handle account administration and compliance paperwork',
      'Take meeting notes and complete follow-ups',
      'Answer client service questions',
    ],
    typical_decisions: [
      'Which stated goal is actually the binding constraint',
      'How to raise a risk the client does not want to hear',
      'When a client request should be declined',
    ],
    common_deliverables: ['Financial plans', 'Client review packs', 'Scenario models', 'Follow-up summaries'],
    tools_used: ['Planning software such as eMoney or RightCapital', 'CRM', 'Excel', 'Custodial platforms'],
    skills_used: ['Listening', 'Explaining money to non-experts', 'Planning technique', 'Relationship building'],
    work_environment: 'Client-facing and relationship-driven, in an office or hybrid, with regulated processes around advice.',
    work_schedule_notes: 'Mostly regular hours, with evening client meetings and business development outside them. Compensation often depends on growing a client base.',
    common_misconceptions: [
      'That it is investing. It is mostly planning, tax, insurance and behaviour.',
      'That clients want optimal answers. They want to be understood.',
      'That you can avoid business development. Long-term success depends on it.',
    ],
    cannot_be_simulated: [
      'A client panicking in a market fall',
      'Depending on relationships for your income',
      'A client relationship deepening or souring over years',
    ],
    characteristics: [
      ['client_interaction', 'high', 'The relationship is the job.', true],
      ['persuasion', 'high', 'Advice only counts if it is followed.', true],
      ['detail_orientation', 'high', 'Plan and compliance errors matter.', true],
      ['structured_environments', 'high', 'Regulated and process-bound.', true],
      ['quantitative_intensity', 'medium', 'Scenario maths, not heavy modelling.', true],
      ['writing', 'medium', 'Plans and follow-ups in plain language.', true],
      ['repetitive_precision', 'medium', 'Recurring reviews and paperwork.', true],
      ['autonomy', 'medium', 'Grows with your own client book.', true],
      ['mission_orientation', 'medium', 'Many advisers describe it as helping families.', false],
    ],
    sources: [
      onet('Personal Financial Advisors (13-2052.00)', 'https://www.onetonline.org/link/summary/13-2052.00'),
      bls('Personal Financial Advisors', 'https://www.bls.gov/ooh/business-and-financial/personal-financial-advisors.htm'),
    ],
  },

  {
    key: 'commercial_banking',
    title: 'Commercial and Corporate Banking',
    family: 'Finance',
    seniority_scope: 'Credit analyst or relationship associate',
    match_terms: ['commercial banking', 'corporate banking', 'credit analyst', 'lending'],
    core_tasks: [
      'Analyse a borrower\u2019s financial statements and cash flow',
      'Write credit memos with a recommendation and covenants',
      'Monitor existing loans for covenant and performance problems',
      'Support relationship managers in client meetings',
      'Price and structure facilities within policy',
    ],
    entry_level_responsibilities: [
      'Spread financial statements accurately',
      'Draft credit memos for review',
      'Maintain the monitoring file on a portfolio',
      'Prepare client meeting materials',
    ],
    typical_decisions: [
      'Whether cash flow genuinely supports the requested facility',
      'Which risk becomes a condition rather than a decline',
      'When to raise a deteriorating borrower internally',
    ],
    common_deliverables: ['Credit memos', 'Financial spreads', 'Monitoring reports', 'Client proposals'],
    tools_used: ['Excel', 'Credit and spreading systems', 'Bank policy manuals', 'Industry data'],
    skills_used: ['Credit analysis', 'Written argument', 'Judgement within policy', 'Client contact'],
    work_environment: 'Structured and policy-bound, in an office, with clear approval hierarchies and named accountability for each credit.',
    work_schedule_notes: 'Generally predictable hours by finance standards, with pressure around approvals and annual reviews.',
    common_misconceptions: [
      'That it is deal work. It is mostly written analysis and monitoring.',
      'That the answer is the number. The memo must persuade a committee.',
      'That client contact is limited. Relationship work grows quickly.',
    ],
    cannot_be_simulated: [
      'A borrower you approved failing',
      'Client relationships across an economic cycle',
      'Answering to a credit committee repeatedly',
    ],
    characteristics: [
      ['writing', 'high', 'The credit memo is the product.', true],
      ['analytical_depth', 'high', 'Cash flow and structure analysis.', true],
      ['detail_orientation', 'high', 'Spreads and covenants must be exact.', true],
      ['quantitative_intensity', 'high', 'Financial statement work daily.', true],
      ['structured_environments', 'high', 'Policy defines what is possible.', true],
      ['repetitive_precision', 'high', 'Annual reviews and monitoring repeat.', true],
      ['client_interaction', 'medium', 'Growing with seniority.', true],
      ['high_pressure_pace', 'low', 'Deadlines exist but are usually planned.', true],
    ],
    sources: [
      onet('Credit Analysts (13-2041.00)', 'https://www.onetonline.org/link/summary/13-2041.00'),
      bls('Financial Analysts', 'https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm'),
    ],
  },

  {
    key: 'product_management',
    title: 'Product Management',
    family: 'Technology',
    seniority_scope: 'Associate or first PM role',
    match_terms: ['product management', 'technical product manager', 'product manager', 'product owner'],
    core_tasks: [
      'Decide what gets built next and what does not',
      'Write specifications engineers can build from',
      'Talk to users about problems rather than features',
      'Resolve conflicts between engineering, design, sales and support',
      'Measure whether a shipped change worked',
    ],
    entry_level_responsibilities: [
      'Own a small surface area end to end',
      'Write tickets and acceptance criteria',
      'Run user interviews and summarise findings',
      'Keep stakeholders informed about what is slipping',
    ],
    typical_decisions: [
      'Which of several legitimate requests to cut this cycle',
      'Whether a problem is worth solving at all',
      'How much to specify before engineering starts',
    ],
    common_deliverables: ['Specifications', 'Prioritised backlogs', 'Research summaries', 'Launch and metrics reviews'],
    tools_used: ['Jira or Linear', 'Analytics tools', 'Figma', 'Written docs'],
    skills_used: ['Prioritisation', 'Written clarity', 'Stakeholder management', 'Data interpretation'],
    work_environment: 'Cross-functional teams, constant meetings, and influence without direct authority over the people doing the work.',
    work_schedule_notes: 'Fragmented, meeting-heavy days with writing pushed to the edges. Launches create spikes.',
    common_misconceptions: [
      'That PMs are mini-CEOs. You usually cannot instruct anyone.',
      'That the job is ideas. The job is deciding what to drop and defending it.',
      'That technical depth is the main constraint. Communication usually is.',
    ],
    cannot_be_simulated: [
      'Being accountable for an outcome you cannot directly control',
      'A team that quietly disagrees with your call for months',
      'Living with a decision through the whole build',
    ],
    characteristics: [
      ['ambiguity_tolerance', 'high', 'Problems arrive undefined and stay that way.', true],
      ['presenting', 'high', 'Constant explanation of decisions.', true],
      ['persuasion', 'high', 'Influence without authority.', true],
      ['teamwork', 'high', 'The whole job is cross-functional.', true],
      ['writing', 'high', 'Specs and decision documents.', true],
      ['analytical_depth', 'medium', 'Data-informed, rarely deep modelling.', true],
      ['client_interaction', 'medium', 'User interviews and customer calls.', true],
      ['short_feedback_loops', 'medium', 'Shipping gives fast, noisy signal.', true],
      ['quantitative_intensity', 'medium', 'Metrics literacy, not heavy maths.', true],
      ['autonomy', 'medium', 'High on what, low on how it is built.', true],
    ],
    sources: [
      onet('Computer and Information Systems Managers (11-3021.00)', 'https://www.onetonline.org/link/summary/11-3021.00'),
      bls('Computer and Information Systems Managers', 'https://www.bls.gov/ooh/management/computer-and-information-systems-managers.htm'),
    ],
  },

  {
    key: 'software_engineering',
    title: 'Software Engineering',
    family: 'Technology',
    seniority_scope: 'Junior engineer, first two years',
    match_terms: ['software engineering', 'software engineer', 'enterprise software', 'developer', 'backend', 'frontend'],
    core_tasks: [
      'Read existing code before writing any',
      'Implement changes in a large codebase you did not write',
      'Debug problems from incomplete reports',
      'Review other people\u2019s code and respond to review of your own',
      'Keep systems running, including on-call work in many teams',
    ],
    entry_level_responsibilities: [
      'Ship small, well-tested changes',
      'Write tests and documentation',
      'Fix bugs in unfamiliar areas',
      'Ask for help early rather than stalling',
    ],
    typical_decisions: [
      'Whether to fix the cause or the symptom given the deadline',
      'How much to refactor while passing through',
      'When a task is blocked enough to escalate',
    ],
    common_deliverables: ['Merged pull requests', 'Tests', 'Technical documentation', 'Incident notes'],
    tools_used: ['Git', 'An IDE', 'CI systems', 'Observability and logging tools'],
    skills_used: ['Reading code', 'Debugging', 'Precision', 'Written technical communication'],
    work_environment: 'Long stretches of focused solo work punctuated by review and standups. Often remote or hybrid.',
    work_schedule_notes: 'Usually regular hours, with on-call rotations and release pressure in many teams.',
    common_misconceptions: [
      'That the job is writing new code. Most of it is reading and changing existing code.',
      'That it is solitary. Code review and design discussion are constant.',
      'That debugging is occasional. It is a large fraction of the week.',
    ],
    cannot_be_simulated: [
      'A codebase with a decade of history and nobody left who wrote it',
      'Being on call when production breaks at 3am',
      'Sustained review by more experienced engineers',
    ],
    characteristics: [
      ['analytical_depth', 'high', 'Debugging is sustained reasoning.', true],
      ['detail_orientation', 'high', 'A character can break a system.', true],
      ['independent_work', 'high', 'Long focused solo stretches.', true],
      ['short_feedback_loops', 'high', 'Tests and builds answer immediately.', true],
      ['ambiguity_tolerance', 'medium', 'Requirements are often incomplete.', true],
      ['teamwork', 'medium', 'Review and design are collaborative.', true],
      ['structured_environments', 'medium', 'Process varies widely by team.', true],
      ['creativity', 'medium', 'Design choices inside real constraints.', true],
      ['client_interaction', 'low', 'Usually mediated by product.', false],
    ],
    sources: [
      onet('Software Developers (15-1252.00)', 'https://www.onetonline.org/link/summary/15-1252.00'),
      bls('Software Developers, Quality Assurance Analysts, and Testers', 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm'),
    ],
  },

  {
    key: 'brand_marketing',
    title: 'Brand, Product and Growth Marketing',
    family: 'Marketing and communications',
    seniority_scope: 'Coordinator or associate',
    match_terms: ['brand', 'marketing', 'communications', 'public relations', ' pr', 'growth', 'performance marketing', 'product marketing', 'brand strategy'],
    core_tasks: [
      'Turn a positioning into copy, assets and campaigns',
      'Run campaigns across channels and report on what happened',
      'Brief and review creative work',
      'Research what customers actually respond to',
      'Coordinate launches across sales, product and agencies',
    ],
    entry_level_responsibilities: [
      'Produce and schedule content and assets',
      'Assemble campaign performance reports',
      'Manage the calendar and chase approvals',
      'Draft copy for review',
    ],
    typical_decisions: [
      'Which message to lead with when several are true',
      'Whether weak results mean the creative, the channel or the offer',
      'What to cut when the launch date will not move',
    ],
    common_deliverables: ['Campaign plans', 'Copy and creative briefs', 'Performance reports', 'Positioning documents'],
    tools_used: ['Analytics platforms', 'Ad managers', 'Email and CRM tools', 'Design and content tools'],
    skills_used: ['Writing', 'Creative judgement', 'Data interpretation', 'Coordination'],
    work_environment: 'Fast and calendar-driven, with many stakeholders and public output. Agency or in-house changes the rhythm significantly.',
    work_schedule_notes: 'Mostly regular hours with launch and campaign spikes; agency work adds client deadlines.',
    common_misconceptions: [
      'That it is mainly creative. Much of it is coordination, approvals and reporting.',
      'That good work is obviously good. Results are noisy and often ambiguous.',
      'That brand and performance work feel similar. They attract different people.',
    ],
    cannot_be_simulated: [
      'Public failure of something you made',
      'Brand building whose effect is never cleanly attributable',
      'Managing an agency relationship over years',
    ],
    characteristics: [
      ['creativity', 'high', 'Original output is expected.', true],
      ['writing', 'high', 'Copy and positioning are written work.', true],
      ['short_feedback_loops', 'high', 'Performance channels answer within days.', true],
      ['teamwork', 'high', 'Nothing ships without other people.', true],
      ['operational_execution', 'high', 'Calendars, approvals, launch mechanics.', true],
      ['persuasion', 'medium', 'Selling ideas internally and to customers.', true],
      ['quantitative_intensity', 'medium', 'Channel analytics, not modelling.', true],
      ['ambiguity_tolerance', 'medium', 'Attribution is rarely clean.', true],
      ['high_pressure_pace', 'medium', 'Launches compress everything.', true],
    ],
    sources: [
      onet('Marketing Managers (11-2021.00)', 'https://www.onetonline.org/link/summary/11-2021.00'),
      bls('Advertising, Promotions, and Marketing Managers', 'https://www.bls.gov/ooh/management/advertising-promotions-and-marketing-managers.htm'),
    ],
  },

  {
    key: 'tech_sales',
    title: 'Technology and Medical Device Sales',
    family: 'Sales and business development',
    seniority_scope: 'SDR, associate rep or clinical specialist',
    match_terms: ['tech sales', 'business development', 'saas sales', 'medical device sales', 'clinical specialist', 'account executive', 'sales'],
    core_tasks: [
      'Find and qualify potential buyers, mostly by being rejected',
      'Run discovery conversations about a buyer\u2019s problem',
      'Demonstrate a product against a specific need',
      'Manage a pipeline and forecast honestly',
      'Negotiate, close and support the handover',
    ],
    entry_level_responsibilities: [
      'High-volume outbound contact and follow-up',
      'Qualify leads and book meetings for senior reps',
      'Keep the CRM accurate',
      'Learn the product well enough to answer objections',
    ],
    typical_decisions: [
      'Which prospects to keep working and which to drop',
      'Whether to push for a close or protect the relationship',
      'How to answer an objection you privately agree with',
    ],
    common_deliverables: ['Qualified pipeline', 'Discovery notes', 'Proposals', 'Accurate forecasts'],
    tools_used: ['CRM such as Salesforce or HubSpot', 'Sales engagement tools', 'Demo environments', 'LinkedIn'],
    skills_used: ['Resilience', 'Listening', 'Persuasion', 'Discipline in follow-up'],
    work_environment: 'Quota-driven and openly measured, with public leaderboards in many teams. Device roles add hospital and clinical settings.',
    work_schedule_notes: 'Regular hours with month and quarter-end intensity; field roles involve travel, and clinical specialists may cover early cases.',
    common_misconceptions: [
      'That it is talking. It is mostly disciplined follow-up and rejection.',
      'That charisma decides. Process and persistence usually decide.',
      'That income is stable. Variable pay makes it uneven.',
    ],
    cannot_be_simulated: [
      'Missing quota with your income attached',
      'Months of rejection in sequence',
      'A public leaderboard you are near the bottom of',
    ],
    characteristics: [
      ['persuasion', 'high', 'The core of the work.', true],
      ['client_interaction', 'high', 'Constant conversation with strangers.', true],
      ['competition', 'high', 'Openly measured against peers.', false],
      ['short_feedback_loops', 'high', 'You know weekly whether it is working.', true],
      ['repetitive_precision', 'high', 'The same outreach motion repeatedly.', true],
      ['risk_tolerance', 'medium', 'Variable compensation.', false],
      ['operational_execution', 'medium', 'Pipeline hygiene is the job under the job.', true],
      ['writing', 'medium', 'Outreach and proposals.', true],
      ['autonomy', 'medium', 'You own your day, not your target.', true],
    ],
    sources: [
      onet('Sales Representatives, Wholesale and Manufacturing (41-4012.00)', 'https://www.onetonline.org/link/summary/41-4012.00'),
      bls('Wholesale and Manufacturing Sales Representatives', 'https://www.bls.gov/ooh/sales/wholesale-and-manufacturing-sales-representatives.htm'),
    ],
  },

  {
    key: 'startup_founder_operator',
    title: 'Startup Founder and Early Operator',
    family: 'Entrepreneurship and operations',
    seniority_scope: 'Founder or first operations hire',
    match_terms: ['founder', 'startup', 'entrepreneur', 'operations associate', 'small business', 'franchise', 'micro-entrepreneur', 'operator'],
    core_tasks: [
      'Decide what the business should do next with no one to ask',
      'Talk to customers and change the plan based on what they say',
      'Build the operational process that makes delivery repeatable',
      'Do whatever is unglamorous and unassigned',
      'Manage money, runway and priorities simultaneously',
    ],
    entry_level_responsibilities: [
      'Own outcomes with no template and no support function',
      'Set up tools and processes from nothing',
      'Handle customers, suppliers and problems directly',
      'Report honestly on what is not working',
    ],
    typical_decisions: [
      'What to stop doing so the important thing gets done',
      'Whether weak early demand means the idea or the execution',
      'When to spend money you may not recover',
    ],
    common_deliverables: ['A working offer customers pay for', 'Operating processes', 'A runway view', 'Customer research'],
    tools_used: ['Spreadsheets', 'No-code and web tools', 'Payment and bookkeeping tools', 'CRM'],
    skills_used: ['Self-direction', 'Prioritisation', 'Selling', 'Tolerance of uncertainty'],
    work_environment: 'Almost no structure, few colleagues, and responsibility that does not stop at the end of the day.',
    work_schedule_notes: 'Unbounded hours and little separation between the work and the rest of life, especially early.',
    common_misconceptions: [
      'That it is freedom. It is responsibility without support.',
      'That the idea matters most. Execution and selling matter more.',
      'That the hard part is building. The hard part is finding demand.',
    ],
    cannot_be_simulated: [
      'Real financial risk to your own money',
      'Sustained uncertainty over years',
      'Being responsible for other people\u2019s livelihoods',
    ],
    characteristics: [
      ['ambiguity_tolerance', 'high', 'Nothing is defined for you.', true],
      ['autonomy', 'high', 'Total, including the parts you do not want.', true],
      ['building_orientation', 'high', 'You build rather than advise.', true],
      ['persuasion', 'high', 'Customers, partners, sometimes investors.', true],
      ['operational_execution', 'high', 'The unglamorous work is yours.', true],
      ['independent_work', 'high', 'Long stretches with nobody checking.', true],
      ['high_pressure_pace', 'high', 'Self-imposed and constant.', true],
      ['risk_tolerance', 'high', 'Financial and career exposure is real.', false],
      ['short_feedback_loops', 'medium', 'Customer signal is fast but noisy.', true],
    ],
    sources: [
      onet('General and Operations Managers (11-1021.00)', 'https://www.onetonline.org/link/summary/11-1021.00'),
      bls('Top Executives', 'https://www.bls.gov/ooh/management/top-executives.htm'),
    ],
  },

  {
    key: 'clinical_medicine',
    title: 'Clinical Medicine (Physician or PA)',
    family: 'Health care delivery',
    seniority_scope: 'Training through early practice',
    match_terms: ['physician', 'clinical physician', 'md', 'physician assistant', 'pa practice', 'doctor', 'medicine'],
    core_tasks: [
      'Take histories and examine patients',
      'Form a differential diagnosis and decide on investigations',
      'Explain diagnosis and options to patients and families',
      'Document encounters and manage the administrative load',
      'Work within a care team across shifts',
    ],
    entry_level_responsibilities: [
      'Carry a patient list under supervision',
      'Present cases concisely to a senior clinician',
      'Complete documentation and orders accurately',
      'Escalate deterioration early',
    ],
    typical_decisions: [
      'Whether a presentation is serious enough to act on now',
      'What to tell a patient who wants certainty you do not have',
      'How to prioritise when several patients need you at once',
    ],
    common_deliverables: ['Clinical notes', 'Care and treatment plans', 'Handover summaries', 'Patient communication'],
    tools_used: ['Electronic health records', 'Clinical guidelines and decision tools', 'Diagnostic equipment'],
    skills_used: ['Clinical reasoning', 'Communication under distress', 'Composure', 'Sustained attention'],
    work_environment: 'Hospitals or clinics, in teams, with continuous interruption and real consequences for error.',
    work_schedule_notes: 'Shift work, nights and weekends in most settings, plus documentation beyond scheduled hours.',
    common_misconceptions: [
      'That it is mostly diagnosis. Documentation and administration take a large share of the day.',
      'That most cases are complex. Much of practice is common problems, repeatedly.',
      'That emotional weight is occasional. It is routine and cumulative.',
    ],
    cannot_be_simulated: [
      'Responsibility for a patient who deteriorates',
      'Delivering serious news to a real family',
      'Night shifts and cumulative fatigue over years',
    ],
    characteristics: [
      ['detail_orientation', 'high', 'Errors carry clinical consequences.', true],
      ['analytical_depth', 'high', 'Diagnostic reasoning under time pressure.', true],
      ['client_interaction', 'high', 'Patients and families constantly.', true],
      ['high_pressure_pace', 'high', 'Interruption is the normal state.', true],
      ['repetitive_precision', 'high', 'Common presentations recur endlessly.', true],
      ['structured_environments', 'high', 'Protocol-bound.', true],
      ['teamwork', 'high', 'Care is delivered by a team.', true],
      ['ambiguity_tolerance', 'high', 'Diagnosis is often uncertain.', true],
      ['mission_orientation', 'high', 'The purpose is explicit.', false],
      ['autonomy', 'low', 'Low in training, higher later.', false],
    ],
    sources: [
      onet('Family Medicine Physicians (29-1215.00)', 'https://www.onetonline.org/link/summary/29-1215.00'),
      bls('Physicians and Surgeons', 'https://www.bls.gov/ooh/healthcare/physicians-and-surgeons.htm'),
    ],
  },

  {
    key: 'nursing_clinical_care',
    title: 'Nursing and Direct Clinical Care',
    family: 'Health care delivery',
    seniority_scope: 'New graduate to early practice',
    match_terms: ['nursing', 'clinical nursing', 'registered nurse', 'medical laboratory science', 'allied health', 'clinical care'],
    core_tasks: [
      'Assess and monitor patients across a shift',
      'Administer medication and treatments exactly',
      'Coordinate with physicians, families and other services',
      'Document care and handover clearly',
      'Notice deterioration before it becomes an emergency',
    ],
    entry_level_responsibilities: [
      'Carry a patient assignment under a preceptor',
      'Complete medication rounds without error',
      'Escalate concerns promptly',
      'Keep documentation current through the shift',
    ],
    typical_decisions: [
      'Which patient needs you first',
      'When an observation warrants escalation',
      'How to advocate for a patient against time pressure',
    ],
    common_deliverables: ['Care documentation', 'Handover reports', 'Patient and family education', 'Escalation communication'],
    tools_used: ['Electronic health records', 'Monitoring equipment', 'Medication systems'],
    skills_used: ['Prioritisation', 'Precision', 'Empathy under pressure', 'Physical stamina'],
    work_environment: 'Wards, units or labs, physically demanding, with continuous human contact and shift handovers.',
    work_schedule_notes: 'Twelve-hour shifts, nights, weekends and holidays are standard in most settings.',
    common_misconceptions: [
      'That it is following physician instructions. Independent assessment and advocacy are central.',
      'That the emotional load is manageable by default. It is a leading reason people leave.',
      'That it is not technical. Medication and monitoring precision are exacting.',
    ],
    cannot_be_simulated: [
      'Physical demands of a twelve-hour shift',
      'Being responsible when a patient deteriorates',
      'Working nights over years',
    ],
    characteristics: [
      ['detail_orientation', 'high', 'Medication precision is non-negotiable.', true],
      ['client_interaction', 'high', 'Continuous patient and family contact.', true],
      ['high_pressure_pace', 'high', 'Multiple patients competing for you.', true],
      ['repetitive_precision', 'high', 'The same protocols every shift.', true],
      ['structured_environments', 'high', 'Protocol and policy driven.', true],
      ['teamwork', 'high', 'Shift-based interdependence.', true],
      ['operational_execution', 'high', 'The shift has to run.', true],
      ['mission_orientation', 'high', 'Explicit care purpose.', false],
      ['autonomy', 'medium', 'Real clinical judgement within scope.', true],
    ],
    sources: [
      onet('Registered Nurses (29-1141.00)', 'https://www.onetonline.org/link/summary/29-1141.00'),
      bls('Registered Nurses', 'https://www.bls.gov/ooh/healthcare/registered-nurses.htm'),
    ],
  },

  {
    key: 'healthcare_administration',
    title: 'Healthcare Administration',
    family: 'Health systems',
    seniority_scope: 'Analyst, coordinator or administrative fellow',
    match_terms: ['healthcare administration', 'health services management', 'hospital administration', 'practice management', 'health operations'],
    core_tasks: [
      'Improve how a clinical service runs without disrupting care',
      'Analyse throughput, staffing, cost and quality data',
      'Coordinate between clinicians, finance and executives',
      'Write proposals and business cases for change',
      'Track whether an implemented change held',
    ],
    entry_level_responsibilities: [
      'Own a reporting pack or a small improvement project',
      'Gather data from clinical and financial systems',
      'Run meetings and follow up on actions',
      'Draft materials for leadership',
    ],
    typical_decisions: [
      'Which bottleneck is worth attacking first',
      'How to change a process clinicians resent changing',
      'What to escalate when a project is quietly failing',
    ],
    common_deliverables: ['Operational dashboards', 'Improvement proposals', 'Business cases', 'Implementation plans'],
    tools_used: ['Excel', 'BI tools', 'EHR reporting modules', 'Project trackers'],
    skills_used: ['Data analysis', 'Stakeholder management', 'Process design', 'Written persuasion'],
    work_environment: 'Hospital or system offices adjacent to clinical areas, with slow decision cycles and many stakeholders.',
    work_schedule_notes: 'Largely regular hours, with escalations when clinical operations are affected.',
    common_misconceptions: [
      'That you decide. Mostly you persuade clinicians who can decline.',
      'That change is fast. Health systems change slowly and reverse often.',
      'That clinical knowledge is not needed. Credibility depends on it.',
    ],
    cannot_be_simulated: [
      'Clinical staff resisting a change you own',
      'Consequences of an operational decision reaching patients',
      'Years-long system change',
    ],
    characteristics: [
      ['analytical_depth', 'high', 'Operational analysis is the base of the work.', true],
      ['persuasion', 'high', 'Change happens by agreement, not instruction.', true],
      ['teamwork', 'high', 'Every project crosses functions.', true],
      ['operational_execution', 'high', 'Implementation is the real test.', true],
      ['structured_environments', 'high', 'Highly regulated setting.', true],
      ['long_project_cycles', 'high', 'Change takes quarters or years.', false],
      ['mission_orientation', 'high', 'Patient care sits behind the numbers.', false],
      ['quantitative_intensity', 'medium', 'Throughput, staffing and cost data.', true],
      ['writing', 'medium', 'Proposals and business cases.', true],
    ],
    sources: [
      onet('Medical and Health Services Managers (11-9111.00)', 'https://www.onetonline.org/link/summary/11-9111.00'),
      bls('Medical and Health Services Managers', 'https://www.bls.gov/ooh/management/medical-and-health-services-managers.htm'),
    ],
  },

  {
    key: 'health_policy_research',
    title: 'Health Policy and Policy Research',
    family: 'Policy and research',
    seniority_scope: 'Research assistant or policy analyst',
    match_terms: ['health policy', 'policy research', 'policy analyst', 'consumer psychology researcher', 'researcher', 'think tank'],
    core_tasks: [
      'Review evidence on a policy question and summarise it honestly',
      'Analyse data sets to test a policy claim',
      'Write briefs for people who will not read the full paper',
      'Track legislation and regulatory change',
      'Present findings to non-technical audiences',
    ],
    entry_level_responsibilities: [
      'Run literature reviews and keep a defensible evidence trail',
      'Clean and analyse data under supervision',
      'Draft sections of briefs and reports',
      'Fact-check everything that goes out',
    ],
    typical_decisions: [
      'What the evidence does and does not support',
      'How to write a brief without overstating a finding',
      'Which question is answerable with the data available',
    ],
    common_deliverables: ['Policy briefs', 'Literature reviews', 'Data analyses', 'Stakeholder presentations'],
    tools_used: ['Stata, R or Python', 'Reference managers', 'Public data sets', 'Writing tools'],
    skills_used: ['Research design', 'Writing for non-specialists', 'Quantitative analysis', 'Intellectual honesty'],
    work_environment: 'Research organisations, government or academia, with long timelines and heavy writing.',
    work_schedule_notes: 'Usually regular hours, with deadline compression around legislative or publication dates.',
    common_misconceptions: [
      'That good evidence changes policy. Often it does not, or not for years.',
      'That the work is debate. Most of it is careful reading and writing alone.',
      'That the analysis is the hard part. Writing it so it is used is harder.',
    ],
    cannot_be_simulated: [
      'Watching good evidence be ignored',
      'Multi-year research cycles',
      'Political pressure on what you can publish',
    ],
    characteristics: [
      ['research', 'high', 'Open-ended investigation is the job.', true],
      ['writing', 'high', 'Briefs and reports are the output.', true],
      ['analytical_depth', 'high', 'Sustained work on one question.', true],
      ['independent_work', 'high', 'Long solo reading and writing.', true],
      ['detail_orientation', 'high', 'A misquoted statistic ends your credibility.', true],
      ['long_project_cycles', 'high', 'Results land months or years later.', false],
      ['mission_orientation', 'high', 'The point is the public outcome.', false],
      ['quantitative_intensity', 'medium', 'Varies from heavy to none by role.', true],
      ['presenting', 'medium', 'Findings must reach non-experts.', true],
    ],
    sources: [
      onet('Political Scientists (19-3094.00)', 'https://www.onetonline.org/link/summary/19-3094.00'),
      bls('Political Scientists', 'https://www.bls.gov/ooh/life-physical-and-social-science/political-scientists.htm'),
    ],
  },

  {
    key: 'nonprofit_program',
    title: 'Nonprofit Program and Community Work',
    family: 'Social impact',
    seniority_scope: 'Coordinator or program associate',
    match_terms: ['non-profit', 'nonprofit', 'program lead', 'community', 'social impact', 'ngo', 'philanthropy'],
    core_tasks: [
      'Run a program day to day, including the logistics nobody sees',
      'Work directly with the people the program serves',
      'Report to funders on outcomes, honestly and on time',
      'Recruit and support volunteers or partners',
      'Do more than the budget really allows',
    ],
    entry_level_responsibilities: [
      'Own logistics and scheduling for program delivery',
      'Collect and record outcome data',
      'Draft funder and board updates',
      'Handle participant communication',
    ],
    typical_decisions: [
      'Which part of the program to cut when funding falls',
      'How to report a disappointing outcome to a funder',
      'When to say no to a need you cannot meet',
    ],
    common_deliverables: ['Program delivery', 'Funder reports', 'Outcome data', 'Volunteer coordination'],
    tools_used: ['Spreadsheets', 'CRM or case management systems', 'Grant reporting portals', 'Communication tools'],
    skills_used: ['Organisation', 'Empathy', 'Writing for funders', 'Doing a lot with little'],
    work_environment: 'Small teams, limited resources, direct contact with the people served, and funder accountability above.',
    work_schedule_notes: 'Often regular hours with evening and weekend events; workload frequently exceeds the staffing.',
    common_misconceptions: [
      'That mission makes the work feel good daily. Resource constraints dominate.',
      'That it is less administrative. Funder reporting is heavy.',
      'That impact is easy to see. Measuring it honestly is hard.',
    ],
    cannot_be_simulated: [
      'Turning someone away for lack of funding',
      'Emotional weight of sustained direct service',
      'Grant cycles determining whether your job exists',
    ],
    characteristics: [
      ['client_interaction', 'high', 'Direct contact with participants.', true],
      ['operational_execution', 'high', 'Programs run on logistics.', true],
      ['writing', 'high', 'Funder reporting is constant.', true],
      ['teamwork', 'high', 'Small interdependent teams.', true],
      ['mission_orientation', 'high', 'The reason most people are there.', false],
      ['detail_orientation', 'medium', 'Grant compliance is exacting.', true],
      ['autonomy', 'medium', 'Wide responsibility, thin support.', true],
      ['ambiguity_tolerance', 'medium', 'Plans change with funding.', true],
    ],
    sources: [
      onet('Social and Community Service Managers (11-9151.00)', 'https://www.onetonline.org/link/summary/11-9151.00'),
      bls('Social and Community Service Managers', 'https://www.bls.gov/ooh/management/social-and-community-service-managers.htm'),
    ],
  },

  {
    key: 'education_program',
    title: 'Education and Museum Programming',
    family: 'Education',
    seniority_scope: 'Educator or program coordinator',
    match_terms: ['museum education', 'education', 'teaching', 'educational programming', 'curriculum', 'instructional'],
    core_tasks: [
      'Design learning experiences for a specific audience',
      'Deliver sessions in person, repeatedly, to varying groups',
      'Adapt on the spot when a session is not landing',
      'Assess whether learning actually happened',
      'Coordinate with schools, families and colleagues',
    ],
    entry_level_responsibilities: [
      'Deliver existing programs to groups',
      'Prepare materials and spaces',
      'Collect feedback and attendance data',
      'Support curriculum revision',
    ],
    typical_decisions: [
      'What to drop when a session runs short of time',
      'How to handle a group that is not engaged',
      'Which learning goal matters most for this audience',
    ],
    common_deliverables: ['Session and curriculum plans', 'Delivered programs', 'Learning materials', 'Feedback summaries'],
    tools_used: ['Curriculum frameworks', 'Presentation and craft materials', 'Booking systems', 'Feedback tools'],
    skills_used: ['Public delivery', 'Design of learning', 'Improvisation', 'Patience'],
    work_environment: 'Classrooms, galleries or community spaces, performing in front of groups for much of the day.',
    work_schedule_notes: 'School-calendar or opening-hours bound, with weekend and holiday programming common in museums.',
    common_misconceptions: [
      'That subject expertise is the main requirement. Delivery and group management matter more.',
      'That each session is new. You will deliver the same content many times.',
      'That it is quiet work. It is performance, most of the day.',
    ],
    cannot_be_simulated: [
      'Holding a room of thirty children for an hour',
      'The same program delivered two hundred times',
      'Long-term effect on a learner you cannot observe',
    ],
    characteristics: [
      ['presenting', 'high', 'You are performing, repeatedly.', true],
      ['client_interaction', 'high', 'Continuous contact with groups.', true],
      ['creativity', 'high', 'Designing how something is understood.', true],
      ['repetitive_precision', 'high', 'The same session, many times.', true],
      ['mission_orientation', 'high', 'Learning is the point.', false],
      ['teamwork', 'medium', 'Coordination with colleagues and schools.', true],
      ['operational_execution', 'medium', 'Materials, space, timing.', true],
      ['ambiguity_tolerance', 'medium', 'Every group behaves differently.', true],
    ],
    sources: [
      onet('Museum Technicians and Conservators (25-4013.00)', 'https://www.onetonline.org/link/summary/25-4013.00'),
      bls('Archivists, Curators, and Museum Workers', 'https://www.bls.gov/ooh/education-training-and-library/curators-museum-technicians-and-conservators.htm'),
    ],
  },

  {
    key: 'law_practice',
    title: 'Law (Practising Attorney)',
    family: 'Legal',
    seniority_scope: 'Junior associate',
    match_terms: ['law', 'lawyer', 'attorney', 'legal', 'litigation', 'corporate law'],
    core_tasks: [
      'Research a legal question and write the answer down precisely',
      'Draft and review documents where wording carries risk',
      'Review large volumes of material for what matters',
      'Advise on what a client may and may not do',
      'Manage deadlines that cannot be missed',
    ],
    entry_level_responsibilities: [
      'Legal research and memoranda',
      'First drafts of documents, reviewed heavily',
      'Document review, often at volume',
      'Recording billable time accurately',
    ],
    typical_decisions: [
      'How much risk to flag when the client wants a clean answer',
      'Which authority actually governs the question',
      'What to raise with the partner rather than resolve alone',
    ],
    common_deliverables: ['Research memoranda', 'Drafted agreements or filings', 'Review summaries', 'Client advice letters'],
    tools_used: ['Westlaw or LexisNexis', 'Document management systems', 'Drafting templates', 'Time recording software'],
    skills_used: ['Precise writing', 'Sustained reading', 'Attention to detail', 'Working to hard deadlines'],
    work_environment: 'Firm or in-house teams, hierarchical, with billable-hour expectations in private practice.',
    work_schedule_notes: 'Long and unpredictable hours in private practice, driven by deals, filings and client demands.',
    common_misconceptions: [
      'That it is advocacy. Most junior work is reading and writing alone.',
      'That courtroom work is common. Most matters never reach a hearing.',
      'That billable hours are an administrative detail. They shape the whole day.',
    ],
    cannot_be_simulated: [
      'Billable-hour pressure over a year',
      'Consequences of a drafting error on a real client',
      'Partner review culture over time',
    ],
    characteristics: [
      ['writing', 'high', 'Precision writing is the craft.', true],
      ['detail_orientation', 'high', 'A word can change liability.', true],
      ['research', 'high', 'Legal research is continuous.', true],
      ['independent_work', 'high', 'Long solo reading and drafting.', true],
      ['repetitive_precision', 'high', 'Document review at volume.', true],
      ['structured_environments', 'high', 'Procedure and hierarchy.', true],
      ['high_pressure_pace', 'high', 'Immovable deadlines.', true],
      ['client_interaction', 'medium', 'Limited early, central later.', true],
      ['autonomy', 'low', 'Very low as a junior.', true],
    ],
    sources: [
      onet('Lawyers (23-1011.00)', 'https://www.onetonline.org/link/summary/23-1011.00'),
      bls('Lawyers', 'https://www.bls.gov/ooh/legal/lawyers.htm'),
    ],
  },

  {
    key: 'commercial_real_estate',
    title: 'Commercial Real Estate Brokerage',
    family: 'Real estate',
    seniority_scope: 'Analyst or junior broker',
    match_terms: ['real estate', 'commercial real estate', 'brokerage', 'property'],
    core_tasks: [
      'Build market surveys and underwriting models for properties',
      'Prospect owners and tenants continuously',
      'Tour properties and represent them credibly',
      'Negotiate terms between parties who both want more',
      'Maintain relationships over years, not months',
    ],
    entry_level_responsibilities: [
      'Underwrite deals and build market data',
      'Produce pitch and marketing materials',
      'Cold call and follow up at volume',
      'Support senior brokers in tours and negotiations',
    ],
    typical_decisions: [
      'Which prospects deserve time this quarter',
      'How aggressive an underwriting assumption can honestly be',
      'When to push a negotiation and when to pause it',
    ],
    common_deliverables: ['Underwriting models', 'Market surveys', 'Offering materials', 'Signed leases or sales'],
    tools_used: ['Excel and Argus', 'CoStar', 'CRM', 'Mapping and market data tools'],
    skills_used: ['Underwriting', 'Persistence', 'Negotiation', 'Relationship building'],
    work_environment: 'Commission-driven and relationship-led, mixing desk analysis with constant outbound contact and property visits.',
    work_schedule_notes: 'Flexible hours, but income depends on closings and early years are often thin.',
    common_misconceptions: [
      'That it is analysis. Analysis supports what is fundamentally a sales business.',
      'That income arrives early. Commission ramp-ups are long.',
      'That deals close quickly. Cycles run months to years.',
    ],
    cannot_be_simulated: [
      'Commission-only income risk',
      'Years of relationship building before a first large deal',
      'A deal dying at the last stage',
    ],
    characteristics: [
      ['persuasion', 'high', 'A sales business at heart.', true],
      ['quantitative_intensity', 'high', 'Underwriting is real modelling.', true],
      ['client_interaction', 'high', 'Owners, tenants and investors.', true],
      ['competition', 'high', 'Openly competitive market.', false],
      ['risk_tolerance', 'high', 'Commission income.', false],
      ['autonomy', 'high', 'You run your own desk.', true],
      ['repetitive_precision', 'medium', 'Prospecting repeats endlessly.', true],
      ['long_project_cycles', 'medium', 'Deals take months.', false],
    ],
    sources: [
      onet('Real Estate Brokers (41-9021.00)', 'https://www.onetonline.org/link/summary/41-9021.00'),
      bls('Real Estate Brokers and Sales Agents', 'https://www.bls.gov/ooh/sales/real-estate-brokers-and-sales-agents.htm'),
    ],
  },
];

export const CAREER_BY_KEY = new Map(CAREERS.map(c => [c.key, c]));

export default CAREERS;