import { LegalPage, Clause, Sub, P, Enum, Defs, DataTable, Mail, Ref } from '@/components/legal/LegalPage';
import { EFFECTIVE_DATE, PRIVACY_LAST_UPDATED, MIN_AGE, TEAM } from '@/lib/legal';

const CONTENTS = [
  { id: 'scope', title: 'Scope of This Policy' },
  { id: 'definitions', title: 'Definitions' },
  { id: 'collection', title: 'Personal Information We Collect' },
  { id: 'use', title: 'How We Use Personal Information' },
  { id: 'bases', title: 'Legal Bases for Processing' },
  { id: 'ai', title: 'Automated Processing and AI Generation' },
  { id: 'disclosure', title: 'How We Disclose Personal Information' },
  { id: 'institutions', title: 'Educational Institutions' },
  { id: 'cookies', title: 'Cookies and Local Storage' },
  { id: 'retention', title: 'Retention' },
  { id: 'security', title: 'Security' },
  { id: 'minors', title: 'Children and Minors' },
  { id: 'rights', title: 'Your Rights and Choices' },
  { id: 'california', title: 'Additional Disclosures for California Residents' },
  { id: 'international', title: 'International Users' },
  { id: 'changes', title: 'Changes to This Policy' },
  { id: 'contact', title: 'How to Contact Us' },
];

const CATEGORY_TABLE = [
  [
    'Identifiers',
    'Name, email address, account identifier.',
    'To create and administer your account; to communicate with you.',
    'Life of the account.',
  ],
  [
    'Education information',
    'School or university, major or subjects of interest, year or grade, expected graduation year, class schedule and fixed weekly commitments.',
    'To generate Recommendations and to build the experiment plan and guides associated with them.',
    'Life of the account.',
  ],
  [
    'Student Content',
    'Free-text responses concerning paths under consideration, external expectations, private interests, perceived obstacles and financial priorities; priority ratings; reflections, uploaded proof of work, resume content and outreach drafts.',
    'To generate Recommendations, experiments, guides and drafts; to save your progress.',
    'Life of the account, subject to Section 10.',
  ],
  [
    'Third-party contact information',
    'Names, email addresses and notes concerning individuals you record in the outreach tracker.',
    'To display your outreach records to you.',
    'Life of the account, or until you delete the record.',
  ],
  [
    'Internet and device activity',
    'IP address, browser type, and request logs generated by our Platform Provider.',
    'Security, abuse prevention and diagnosis of faults.',
    'As retained by the Platform Provider in the ordinary course.',
  ],
];

export default function Privacy() {
  return (
    <LegalPage
      title="Privacy Policy"
      effective={EFFECTIVE_DATE}
      updated={PRIVACY_LAST_UPDATED}
      contents={CONTENTS}
      lede={
        <>
          <P>
            This Privacy Policy (the “Policy”) describes how Unscripted (“Unscripted,” “we,”
            “us” or “our”) collects, uses, discloses and retains Personal Information in
            connection with the website at useunscripted.base44.app and the services made
            available through it (together, the “Services”), and describes the rights available
            to individuals who use the Services (“you”).
          </P>
          <P>
            Unscripted is operated by {TEAM} and is not presently organized as a registered
            legal entity. When an operating entity is formed, this Policy will be amended to
            identify that entity and its registered address. Until then, requests and enquiries
            under this Policy should be directed to <Mail />.
          </P>
        </>
      }
    >
      <Clause n="1" id="scope" title="Scope of This Policy">
        <Sub n="1.1" title="Application">
          This Policy applies to Personal Information we collect through the Services, whether
          you use them with or without a registered account.
        </Sub>
        <Sub n="1.2" title="Exclusions">
          This Policy does not apply to information collected by any third party, including any
          third-party website or service accessible through the Services, or to information you
          disclose directly to any person you contact using the Services. Those disclosures are
          governed by the practices of the recipient.
        </Sub>
        <Sub n="1.3" title="Conflict">
          Where this Policy conflicts with a supplemental notice given to you at the point of
          collection, the supplemental notice controls as to the information described in it.
        </Sub>
      </Clause>

      <Clause n="2" id="definitions" title="Definitions">
        <P>In this Policy, the following terms have the meanings given below.</P>
        <Defs
          items={[
            {
              term: 'Personal Information',
              def: 'means information that identifies, relates to, describes, or is reasonably capable of being associated with a particular individual. It does not include aggregated or de-identified information that cannot reasonably be used to identify you.',
            },
            {
              term: 'Student Content',
              def: 'means the text, ratings, files and other material you submit to the Services, together with the material generated for you in response to it.',
            },
            {
              term: 'Recommendations',
              def: 'means the career paths, experiments, mission guides, outreach drafts and similar outputs generated for you through the Services.',
            },
            {
              term: 'Platform Provider',
              def: 'means Base44, the application platform on which the Services are hosted, which provides hosting, database, authentication and model-invocation infrastructure.',
            },
            {
              term: 'AI Providers',
              def: 'means the third-party providers of large language models accessed through the Platform Provider for the purpose of generating Recommendations, currently comprising OpenAI, Google and Anthropic.',
            },
          ]}
        />
      </Clause>

      <Clause n="3" id="collection" title="Personal Information We Collect">
        <Sub n="3.1" title="Information you provide">
          We collect the Personal Information you submit to us, comprising: (i) account
          information, being your email address and the credentials used to authenticate you, or,
          where you elect to sign in with Google, the name, email address and profile image
          released to us by that provider; (ii) profile information submitted during onboarding,
          including your name, institution, major or subjects of interest, year or grade,
          expected graduation year and available weekly capacity; and (iii) Student Content.
        </Sub>
        <Sub n="3.2" title="Information collected automatically">
          The Platform Provider generates server log records in the ordinary course of operating
          the Services, including IP address, browser type and request metadata. We use a
          strictly necessary authentication cookie and your browser’s local storage as described
          in Section 9.
        </Sub>
        <Sub n="3.3" title="Analytics">
          The Platform Provider collects first-party analytics on our behalf as part of the
          infrastructure on which the Services run, comprising page views, session activity and
          named product usage events recording the steps you complete within the Services. We do
          not operate third-party analytics, advertising, or session-recording technologies on the
          Services, and we do not permit third parties to collect Personal Information through the
          Services for their own purposes.
        </Sub>
        <Sub n="3.4" title="Information concerning other individuals">
          If you record the details of another individual in the outreach features, you are
          responsible for ensuring that you obtained those details lawfully and that your use of
          them is lawful.
        </Sub>
        <Sub n="3.5" title="Sensitive information">
          We do not request, and ask that you do not submit, information concerning your health,
          racial or ethnic origin, religious or philosophical beliefs, sexual orientation,
          immigration status, precise geolocation, government identifiers or financial account
          details. The Services have no function requiring that information.
        </Sub>
        <Sub n="3.6" title="Categories collected">
          The categories of Personal Information we collect, the purposes for which each category
          is used, and the period for which each is retained, are as follows.
        </Sub>
        <DataTable
          caption="Table 1 — Categories of Personal Information collected in the preceding twelve (12) months."
          columns={['Category', 'Examples', 'Purpose of collection', 'Retention']}
          rows={CATEGORY_TABLE}
        />
      </Clause>

      <Clause n="4" id="use" title="How We Use Personal Information">
        <P>We use Personal Information for the following purposes:</P>
        <Enum
          items={[
            'to generate Recommendations from the information you submit, and to produce the experiment plans, mission guides and outreach drafts associated with them;',
            'to create, authenticate and administer your account, and to preserve your progress between sessions;',
            'to respond to your enquiries and provide support;',
            'to maintain the security and integrity of the Services, to prevent and investigate abuse, and to diagnose faults;',
            'to understand, in aggregate, which parts of the Services are used and which fail, and to improve them accordingly; and',
            'to comply with applicable law and to establish, exercise or defend legal claims.',
          ]}
        />
        <Sub n="4.1" title="No advertising use">
          We do not use Personal Information for targeted or behavioral advertising, and we do
          not use Student Content to profile you for any purpose other than generating your own
          Recommendations.
        </Sub>
        <Sub n="4.2" title="Model training">
          We do not train, fine-tune or otherwise develop machine-learning models on Student
          Content.
        </Sub>
      </Clause>

      <Clause n="5" id="bases" title="Legal Bases for Processing (EEA and United Kingdom)">
        <P>
          Where the General Data Protection Regulation or the UK GDPR applies to our processing,
          we rely on the following legal bases:
        </P>
        <Enum
          items={[
            'performance of a contract with you, for the processing necessary to provide the Services you have requested, including the generation of Recommendations (Article 6(1)(b));',
            'our legitimate interests in securing the Services, preventing abuse and improving the product, where those interests are not overridden by your interests or fundamental rights (Article 6(1)(f));',
            'your consent, where we ask for it, which you may withdraw at any time without affecting the lawfulness of processing carried out before withdrawal (Article 6(1)(a)); and',
            'compliance with a legal obligation to which we are subject (Article 6(1)(c)).',
          ]}
        />
        <Sub n="5.1" title="Consequence of not providing information">
          Provision of profile information and Student Content is not a statutory requirement, but
          it is necessary to generate Recommendations. If you do not provide it, the Services
          cannot function for you.
        </Sub>
      </Clause>

      <Clause n="6" id="ai" title="Automated Processing and AI Generation">
        <Sub n="6.1" title="How generation works">
          The Services generate Recommendations by transmitting the text you submit, together with
          instructions prepared by us, to the AI Providers through the Platform Provider, and
          returning the resulting output to you. Transmission to the AI Providers is intrinsic to
          the Services and cannot be disabled while continuing to use them.
        </Sub>
        <Sub n="6.2" title="Instruction to users">
          Because your submissions are processed by third-party model providers, you should not
          submit information you would not wish to be processed outside our systems, including
          the categories identified in Section 3.5 and private information concerning other
          individuals.
        </Sub>
        <Sub n="6.3" title="AI Provider practices">
          The AI Providers process submissions under their agreements with the Platform Provider
          and may retain inputs for a limited period for abuse monitoring in accordance with those
          agreements. We do not control the internal practices of the AI Providers beyond those
          agreements.
        </Sub>
        <Sub n="6.4" title="No automated decision-making with legal effect">
          Recommendations are advisory outputs presented to you for your consideration. We do not
          use automated processing to make decisions producing legal effects concerning you or
          similarly significantly affecting you within the meaning of Article 22 of the GDPR. No
          admission, employment, credit, eligibility or similar determination is made by the
          Services.
        </Sub>
        <Sub n="6.5" title="Accuracy">
          Recommendations are machine-generated and may be inaccurate, incomplete or unsuitable
          for your circumstances. The limitations applicable to them, and your obligation to
          verify them, are set out in the <Ref to="/terms">Terms of Service</Ref>.
        </Sub>
      </Clause>

      <Clause n="7" id="disclosure" title="How We Disclose Personal Information">
        <Sub n="7.1" title="Service providers">
          We disclose Personal Information to the following categories of recipient, in each case
          for the limited purpose stated and subject to contractual restrictions on further use:
        </Sub>
        <DataTable
          columns={['Recipient', 'Personal Information disclosed', 'Purpose']}
          rows={[
            ['Platform Provider (Base44)', 'All categories in Table 1.', 'Hosting, database, authentication and infrastructure.'],
            ['AI Providers (OpenAI, Google, Anthropic)', 'Profile information and Student Content submitted for generation.', 'Generation of Recommendations at your request.'],
            ['Google', 'Account identifiers, where you elect to sign in with Google.', 'Authentication.'],
          ]}
        />
        <Sub n="7.2" title="Legal and safety disclosures">
          We may disclose Personal Information where we reasonably believe disclosure is required
          by law, legal process or governmental request, or is necessary to protect the rights,
          property or safety of you, us or any other person.
        </Sub>
        <Sub n="7.3" title="Business transfers">
          If the Services are transferred, in whole or in part, in connection with a merger,
          acquisition, financing or sale of assets, Personal Information may be transferred as
          part of that transaction. We will give notice on this page before Personal Information
          becomes subject to a materially different privacy policy as a result.
        </Sub>
        <Sub n="7.4" title="No sale or sharing">
          We do not sell Personal Information, and we do not share Personal Information for
          cross-context behavioral advertising, as those terms are defined under the California
          Consumer Privacy Act. We have not done so in the preceding twelve (12) months, and we
          do not sell or share the Personal Information of any individual we know to be under
          sixteen (16) years of age.
        </Sub>
      </Clause>

      <Clause n="8" id="institutions" title="Educational Institutions">
        <Sub n="8.1" title="No institutional access by default">
          We do not disclose your Student Content, your Recommendations or your reflections to
          your school, university or any other educational institution.
        </Sub>
        <Sub n="8.2" title="Institutional licensing">
          We intend to license the Services to educational institutions. Where an institution
          licenses the Services, information made available to that institution will be limited
          to aggregated or de-identified information, such as participation and completion rates,
          and will not include the substance of any individual’s submissions.
        </Sub>
        <Sub n="8.3" title="Notice of change">
          If we propose to make individually identifiable information available to an institution,
          we will give affected users notice in advance and will obtain consent where consent is
          required. Declining does not terminate your access to the Services.
        </Sub>
      </Clause>

      <Clause n="9" id="cookies" title="Cookies and Local Storage">
        <Sub n="9.1" title="Strictly necessary cookies">
          We use an authentication cookie for the sole purpose of maintaining your signed-in
          session. It is strictly necessary to the operation of the Services and cannot be
          disabled while you remain signed in.
        </Sub>
        <Sub n="9.2" title="Local storage">
          Your browser’s local storage holds a session identifier set by the Platform Provider,
          which distinguishes one visit from another for the analytics described in Section 3.3.
          Where you begin onboarding without an account, your responses are also stored in your
          browser’s local storage so that they are not lost if you leave the page. That record
          remains on your device until you create an account, clear your browsing data, or the
          stored version is superseded.
        </Sub>
        <Sub n="9.3" title="No advertising technologies">
          We do not set advertising or cross-site tracking cookies, and the Services do not
          respond differently to browser Do Not Track signals because no tracking of that kind
          occurs.
        </Sub>
      </Clause>

      <Clause n="10" id="retention" title="Retention">
        <Sub n="10.1" title="Retention period">
          We retain Personal Information for as long as your account remains open, and thereafter
          only as necessary to comply with legal obligations, resolve disputes and enforce our
          agreements. Retention periods by category are stated in Table 1.
        </Sub>
        <Sub n="10.2" title="Deletion within the Services">
          Items you delete within the Services are moved to a recently deleted state and are
          purged automatically on expiry of that period.
        </Sub>
        <Sub n="10.3" title="Account deletion">
          On request under Section 13, we delete your account and the Personal Information
          associated with it. Residual copies may persist in routine backups maintained by the
          Platform Provider until those backups are overwritten in the ordinary course.
        </Sub>
      </Clause>

      <Clause n="11" id="security" title="Security">
        <Sub n="11.1" title="Measures">
          We maintain administrative and technical measures appropriate to the nature of the
          information we hold, including encryption of traffic in transit, authentication managed
          by the Platform Provider, and restriction of database access to personnel who require it
          to operate the Services.
        </Sub>
        <Sub n="11.2" title="No guarantee">
          No method of transmission or storage is completely secure, and we do not warrant that
          Personal Information will remain free from unauthorized access.
        </Sub>
        <Sub n="11.3" title="Reporting">
          If you believe your account has been compromised, or if you identify a vulnerability in
          the Services, notify us at <Mail />. We will not pursue claims against a person who
          reports a vulnerability in good faith and does not exploit it or access other users’
          data.
        </Sub>
      </Clause>

      <Clause n="12" id="minors" title="Children and Minors">
        <Sub n="12.1" title="Minimum age">
          The Services are not directed to, and may not be used by, children under {MIN_AGE} years
          of age. We do not knowingly collect Personal Information from any child under {MIN_AGE}.
        </Sub>
        <Sub n="12.2" title="Users aged 13 to 17">
          Individuals aged {MIN_AGE} to 17 may use the Services only with the permission of a
          parent or legal guardian, who thereby accepts responsibility for that individual’s use
          of the Services under the <Ref to="/terms">Terms of Service</Ref>.
        </Sub>
        <Sub n="12.3" title="Deletion of information collected from children">
          If we become aware that we have collected Personal Information from a child under
          {' '}{MIN_AGE}, we will delete that information promptly. A parent or legal guardian who
          believes we hold such information should contact us at <Mail />.
        </Sub>
        <Sub n="12.4" title="Parental rights">
          A parent or legal guardian may, on request, review the Personal Information we hold
          concerning their minor child, require its deletion, and refuse to permit further
          collection. We may ask for information reasonably necessary to verify the relationship
          before acting on such a request.
        </Sub>
      </Clause>

      <Clause n="13" id="rights" title="Your Rights and Choices">
        <Sub n="13.1" title="Rights available to all users">
          Irrespective of your place of residence, you may: (i) request access to the Personal
          Information we hold about you; (ii) correct inaccurate information, which you may do
          directly in your account settings; (iii) request deletion of your account and its
          contents; (iv) obtain a copy of the information you have submitted; and (v) withdraw
          any consent you have given.
        </Sub>
        <Sub n="13.2" title="Additional rights under the GDPR">
          If you are in the European Economic Area or the United Kingdom, you additionally have
          the rights to restrict or object to processing, to data portability, and to lodge a
          complaint with your supervisory authority. We would ask that you raise the matter with
          us first.
        </Sub>
        <Sub n="13.3" title="How to exercise your rights">
          Send your request to <Mail /> from the email address associated with your account, or
          provide information sufficient for us to verify that the request is yours. We do not
          require you to create an account or use any particular form.
        </Sub>
        <Sub n="13.4" title="Timing and cost">
          We respond to requests without undue delay and in any event within forty-five (45) days,
          which may be extended once where reasonably necessary and where we notify you of the
          extension. We do not charge a fee for responding to a request unless it is manifestly
          unfounded or excessive.
        </Sub>
        <Sub n="13.5" title="Denial">
          Where we decline a request in whole or in part, we will tell you why, and we will not
          discriminate against you for having made it.
        </Sub>
      </Clause>

      <Clause n="14" id="california" title="Additional Disclosures for California Residents">
        <Sub n="14.1" title="Categories">
          The categories of Personal Information we have collected in the preceding twelve (12)
          months, the sources of that information, the business purposes for its collection and
          the categories of recipient to whom it has been disclosed are set out in Sections 3, 4
          and 7. All Personal Information is collected directly from you, save for the account
          information released by Google where you elect to use that sign-in method.
        </Sub>
        <Sub n="14.2" title="Sensitive personal information">
          We do not collect sensitive personal information for the purpose of inferring
          characteristics, and we do not use or disclose sensitive personal information for any
          purpose other than those permitted without an opt-out right.
        </Sub>
        <Sub n="14.3" title="Sale and sharing">
          We do not sell or share Personal Information. Accordingly, we do not offer a “Do Not
          Sell or Share My Personal Information” link.
        </Sub>
        <Sub n="14.4" title="Your rights">
          California residents have the rights to know, to delete, to correct, and to limit the
          use of sensitive personal information, and the right not to receive discriminatory
          treatment for exercising them. Requests may be submitted as set out in Section 13.3,
          including by an authorized agent who provides written authorization from you.
        </Sub>
      </Clause>

      <Clause n="15" id="international" title="International Users">
        <P>
          The Services are operated in the United States and Personal Information is stored and
          processed there. If you access the Services from outside the United States, you
          acknowledge that your Personal Information will be transferred to and processed in the
          United States, where data protection law may differ from that of your jurisdiction.
          Where required, we rely on the European Commission’s standard contractual clauses, or an
          equivalent transfer mechanism, in respect of such transfers.
        </P>
      </Clause>

      <Clause n="16" id="changes" title="Changes to This Policy">
        <P>
          We may amend this Policy from time to time. The Last Updated date at the head of this
          Policy states when it was most recently amended. Where an amendment materially affects
          the treatment of Personal Information already collected, we will notify account holders
          before the amendment takes effect. Your continued use of the Services after an amendment
          takes effect constitutes acceptance of the amended Policy.
        </P>
      </Clause>

      <Clause n="17" id="contact" title="How to Contact Us">
        <P>
          Questions, requests and complaints under this Policy should be sent to <Mail />. We will
          acknowledge and respond as provided in Section 13.4.
        </P>
      </Clause>
    </LegalPage>
  );
}
